-- AlterTable
ALTER TABLE `Game` ADD COLUMN `lastMoveTimestamp` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `playerOTimeRemaining` INTEGER NOT NULL DEFAULT 60,
    ADD COLUMN `playerXTimeRemaining` INTEGER NOT NULL DEFAULT 60;
